/*
 * File:   coError.h
 * Author: darek
 *
 * Created on 28 październik 2013, 22:07
 */

#ifndef COERROR_H
#define	COERROR_H

#ifdef	__cplusplus
extern "C" {
#endif

#include "coCommon.h"

/** Stackoverflow question 9907160 */
#define FOREACH_CO_ERROR(CO_ERROR)					\
	CO_ERROR(CO_ERR_NO_ERROR=0)						\
	CO_ERROR(CO_ERR_INTRO_FAILED)					\
	CO_ERROR(CO_ERR_NULL_THIS_POINTER)				\
	CO_ERROR(CO_ERR_EXIT_REQUESTED)					\
	CO_ERROR(CO_ERR_NEW_FAILED)						\
	CO_ERROR(CO_ERR_BAD_ALLOC)						\
	CO_ERROR(CO_ERR_BAD_PATH)						\
	CO_ERROR(CO_ERR_CANNOT_OPEN_FILE)				\
	CO_ERROR(CO_ERR_CANNOT_SEEK_FILE)				\
	CO_ERROR(CO_ERR_CANNOT_GET_FILE_SIZE)			\
	CO_ERROR(CO_ERR_FILE_READ_FAILED)				\
	CO_ERROR(CO_ERR_PARENT_BAD_OR_NULL)				\
	CO_ERROR(CO_ERR_CHILD_BAD_OR_NULL)				\
	CO_ERROR(CO_ERR_IS_DESTROYED)					\
	CO_ERROR(CO_ERR_ARRAY_GROW_ZERO_DEF_SIZE)		\
	CO_ERROR(CO_ERR_ARRAY_GROW_INTRO_FAILED)		\
	CO_ERROR(CO_ERR_ARRAY_GROW_DEF_SIZE_ABOVE_MAX)	\
	CO_ERROR(CO_ERR_ARRAY_GROW_EXCEED_MAX_SIZE)		\
	CO_ERROR(CO_ERR_ARRAY_GROW_BAD_CALLOC)			\
	CO_ERROR(CO_ERR_ARRAY_GROW_BAD_REALLOC)			\
	CO_ERROR(CO_ERR_ARRAY_GROW_BAD_FLAG)			\
	CO_ERROR(CO_ERR_ARRAY_GROW_LAST_IND_ABOVE_SIZE)	\
	CO_ERROR(CO_ERR_ARRAY_GROW_NULL_RESULT_ARRAY)	\
	CO_ERROR(CO_ERR_INDEX_OUT_OF_RANGE)				\
	CO_ERROR(CO_ERR_OBJECT_failed_to_alloc_objlist)	\
	CO_ERROR(CO_ERR_MUTEX_FAILED)					\
	CO_ERROR(CO_ERR_MEMORY_LEAKS_DETECTED)			\
	CO_ERROR(CO_ERR_FAILED_ALLOC_MEMORY_INFO)		\
	CO_ERROR(CO_ERR_MEMORY_PASSED_NULL_INFO)		\
	CO_ERROR(CO_ERR_DELETED)						\
	CO_ERROR(CO_ERR_NOT_INITED)						\

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,


typedef enum co_error {
	FOREACH_CO_ERROR(GENERATE_ENUM)
} co_error;

const char *coGetStringError(const co_error co_err);

#ifdef	__cplusplus
}
#endif

#endif	/* COERROR_H */

